### ISSUE TITLE
about train/dev/test splits

### ISSUE THREAD

**Issue by srtianxia** [wasiahmad/ACE05-Processor#1]
Hi,
Thanks for you jobs , but I cannot download the train / dev / test splits filelist, can you provide this file? , my email is srtianxia@gmail.com.

**Comment by wasiahmad** [comment]
It can be found [here](https://drive.google.com/open?id=1tvmrXHy0vrsSwb5IdtWvhFN1Z1EoEk88).

**Comment by srtianxia** [comment]
> It can be found [here](https://drive.google.com/open?id=1tvmrXHy0vrsSwb5IdtWvhFN1Z1EoEk88).

 Thanks a lot!
