### ISSUE TITLE
Arabic events dropped

### ISSUE THREAD

**Issue by edchengg** [wasiahmad/ACE05-Processor#2]
I was checking at the number of events dropped. It seems to be a large percentage of events are dropped for Arabic.
I guess the main problem is the mwt of Arabic tokenizer which expand word into multiple words.
ACE data processing for Arabic is such a pain.

******************** Arabic ********************

-------------------- Train --------------------
[Entities] Total 29232, Skipped 1898, Dropped 3086, Wrong-Head 18.
[Events] Total 1793, Dropped 1719, Wrong-Trigger 0.
[Relations] Total 3848, Dropped 1240.
-------------------- Dev --------------------
[Entities] Total 3148, Skipped 208, Dropped 312, Wrong-Head 0.
[Events] Total 230, Dropped 222, Wrong-Trigger 0.
[Relations] Total 434, Dropped 129.
-------------------- Test --------------------
[Entities] Total 2898, Skipped 196, Dropped 391, Wrong-Head 0.
[Events] Total 247, Dropped  235, Wrong-Trigger 0.
[Relations] Total 449, Dropped 144.

**Comment by wasiahmad** [comment]
Yes, if you are able to solve/mitigate the issue, feel free to make a pull request.
